### ISSUE TITLE
Microsoft.Compute throws resource undefined error

### ISSUE THREAD

**Issue by aheumaier** [Armkit/armkit#30]
**Describe the bug**
`yarn generate` produces the following errror on translating `Microsoft.Compute` :

``` shell
(node:1611264) UnhandledPromiseRejectionWarning: Error: cannot resolve local reference https://schema.management.azure.com/schemas/2019-07-01/Microsoft.Compute.Extensions.json#/definitions/genericExtension
    at TypeGenerator.resolveReference (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/type-generator.js:336:19)
    at TypeGenerator.typeForRef (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/type-generator.js:312:29)
    at /home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/type-generator.js:175:33
    at TypeGenerator.generate (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/type-generator.js:153:13)
    at ImportArmSchema.make (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/import.js:21:23)
    at ImportArmSchema.generateTypeScript (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/import.js:9:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ImportArmSchema.import (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/base.js:41:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1611264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```
**To Reproduce**

**Expected behavior**
No errors

**Comment by skorfmann** [comment]
This throws here: https://github.com/Yetics/armkit/blob/db04484676465aa83065140b1cc76e9444bf7ec5/packages/armkit-cli/lib/type-generator.ts#L386 

Looks like the schema isn't full resolved for some reason?

**Comment by aheumaier** [comment]
Just a local json resover is implemented right now. 
This is one of the rare cases where external url resource resovers are required.
Microsoft.Compute -> Micosoft.ComputeExtention
https://github.com/Yetics/armkit/blob/d23523497615509403ef8a6b1156bda5138efb46/packages/armkit-cli/lib/type-generator.ts#L387
