### ISSUE TITLE
Generating Microsoft.Network  throws errors on handling 'undefined' types

### ISSUE THREAD

**Issue by aheumaier** [Armkit/armkit#31]
**Describe the bug**

**To Reproduce**

 Run `yarn generate`

```shell
yarn run v1.22.5
$ armkit generate
(node:1614299) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toUpperCase' of undefined
    at /home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/type-generator.js:213:53
    at TypeGenerator.generate (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/type-generator.js:153:13)
    at ImportArmSchema.make (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/import.js:21:23)
    at ImportArmSchema.generateTypeScript (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/import.js:9:14)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ImportArmSchema.import (/home/aheumaier/Codebox/src/github.com/yetics/armkit/packages/armkit-cli/lib/base.js:41:13)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:1614299) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:1614299) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 0.61s.
```
**Expected behavior**
no errors

**Comment by skorfmann** [comment]
I think this needs to be added here https://github.com/Yetics/armkit/blob/db04484676465aa83065140b1cc76e9444bf7ec5/packages/armkit-cli/lib/type-generator.ts#L2

**Comment by aheumaier** [comment]
Resolved
