### ISSUE TITLE
Some services have type undefined

### ISSUE THREAD

**Issue by ohthehugemanatee** [Armkit/armkit#75]
**Describe the bug**
When running snapshot tests, some services come back with this error:
```
    TypeError: Cannot read property 'toUpperCase' of undefined

      248 |           }
      249 |         }
    > 250 |         const methodName = 'from' + type[0].toUpperCase() + type.substr(1);
          |                                             ^
      251 |         code.openBlock(`public static ${methodName}(value: ${type}${list}): ${typeName}`);
      252 |         code.line(`return new ${typeName}(value);`);
      253 |         code.closeBlock();

      at lib/type-generator.ts:250:45
      at TypeGenerator.generate (lib/type-generator.ts:194:7)
      at ImportArmSchema.make (lib/import.ts:26:19)
      at ImportArmSchema.generateTypeScript (lib/import.ts:10:10)
      at ImportArmSchema.import (lib/base.ts:61:7)
      at test/schema.test.ts:143:3
```
The following services are effected by this issue:
```
["2018-07-01/Microsoft.Media", "Media"],
["2020-11-01/Microsoft.Network", "Network"],
["2020-12-01/Microsoft.ApiManagement", "ApiManagement"],
["2018-11-01/Microsoft.Web", "Web"],
["2019-06-01/Microsoft.Automation", "Automation"],
```

**To Reproduce**
1. Add one of the effected services to the fixtures file from #68 
2. Run tests
3. See error

**Comment by aheumaier** [comment]
This seems closed for me . Feel free to reopen as issues reemerge.
